### PR TITLE
U/lynnej/cleanup eups

### PR DESCRIPTION
**Pull request by rhiannonlynne**
Small changes in ups table.
More changes in unit tests - removed outdated tests. However, had to also skip a unit test that was not updated for current base code -- this should be fixed (as a separate ticket).

### CODE REVIEW

**Comment by tribeiro** [comment]
Is this ready for a review?

**Comment by tribeiro** [comment]
Please, Squash and merge!

**Comment by rhiannonlynne** [comment]
I do not have permission to merge this PR. Could you please do it for me?

**Comment by rhiannonlynne** [comment]
Thank you!

**Comment by rhiannonlynne** [comment]
Deleted u/lynnej/cleanup_eups

**Pull request merged**
